# Generated by Django 4.1.3 on 2022-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
